openapi: 3.0.0
info:
  title: Todo Frontend API Contract
  version: 1.0.0
  description: API contract for the Todo Frontend application's interaction with the FastAPI backend.
servers:
  - url: /api
    description: Frontend API Base Path
paths:
  /tasks:
    get:
      summary: Get all tasks for the authenticated user
      operationId: getTasks
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
    post:
      summary: Create a new task for the authenticated user
      operationId: createTask
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '422':
          description: Validation Error
  /tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The ID of the task
    put:
      summary: Update an existing task for the authenticated user
      operationId: updateTask
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '404':
          description: Task not found
        '422':
          description: Validation Error
    delete:
      summary: Delete a task for the authenticated user
      operationId: deleteTask
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Task not found
  /tasks/{id}/complete:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The ID of the task
    patch:
      summary: Mark a task as complete or incomplete for the authenticated user
      operationId: toggleTaskCompletion
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
                  description: New completion status of the task
              required:
                - completed
      responses:
        '200':
          description: Task completion status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '404':
          description: Task not found
        '422':
          description: Validation Error
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        title:
          type: string
          minLength: 1
        description:
          type: string
          nullable: true
        completed:
          type: boolean
          default: false
        user_id:
          type: string
          readOnly: true
      required:
        - id
        - title
        - completed
        - user_id
    TaskCreate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
        description:
          type: string
          nullable: true
      required:
        - title
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
        description:
          type: string
          nullable: true
        completed:
          type: boolean
      required:
        - title
        - completed
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
